version: '3.5'

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: project_nginx
    #    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/laravel/frontend/
      - ./backend:/var/www/laravel/backend/
    depends_on:
      - app
      - db
    networks:
      - net_app
  app:
    build:
      context: ./_docker/app/
      dockerfile: app
    container_name: project_app
    volumes:
      - ./frontend:/var/www/laravel/frontend/
      - ./backend:/var/www/laravel/backend/  
    depends_on:
      - db
    #    restart: unless-stopped
    networks:
      - net_app

  db:
    image: mysql:8.0
    restart: always
    container_name: project_db
    ports:
      - 8306:3306
    volumes:
      - ./backend/tmp/db:/var/lib/mysql
    #    env_file:
    #      - ./academy-test-task/backend/.env
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - net_app

  vue:
    build:
      context: .
      dockerfile: ./_docker/vue/vue
    container_name: project_vue
    volumes:
      - ./frontend:/var/www/laravel/frontend/
      - ./backend:/var/www/laravel/backend/
    networks:
      - net_app
    ports:
      - 3000:3000

networks:
  net_app:
    driver: bridge
